# Generated by Django 2.1.5 on 2020-04-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
